config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo.views import base_views

urlpatterns = [
    #/으로 접속시 pybo의 index로 연결되도록
    path('',base_views.index, name='index'),
    path('admin/', admin.site.urls),
    #pybo url을 호출하면 views.py의 index라는 함수를 호출
    #항상 끝에 정규화를 위해 / 를 붙여주자
    #path('pybo/', views.index),
    #pybo url이 요청되면 pybov폴더의 urls.py의 매핑정보를 읽으라는 뜻.
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')), #로그인/아웃을 위한 url추가

]

pybo/urls.py
from django.urls import path

#from . import views
from .views import base_views,answer_views,question_views,comment_views,vote_views,person_views

#앱을 구분하기 위한 이름.(네임스페이스)
app_name = 'pybo'

urlpatterns=[
    #name은 별칭을 말함.html에서 별칭을 사용할 수 있음.
    #pybo가 생략된 이유는 config/urls.py에 이미 명시되어 있기 때문.
    path('',base_views.index, name='index'),
    #상세조회
    path('<int:question_id>/',base_views.detail, name='detail'),
    #답변등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #답변수정
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify, name='answer_modify'),
    #딥뱐삭제
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete, name='answer_delete'),
    #질문등록
    path('question/create/', question_views.question_create,name='question_create'),
    #질문수정
    path('question/modify/<int:question_id>/',question_views.question_modify, name='question_modify'),
    #질문삭제
    path('question/delete/<int:question_id>/',question_views.question_delete, name='question_delete'),
    #댓글 작성,수정,삭제
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    #추천기능
    path('vote/quetion/<int:question_id>/',vote_views.vote_question,name='vote_question'),
    path('vote/answer/<int:answer_id>/',vote_views.vote_answer,name='vote_answer'),

    #특정사용자가 쓴글
    path('person/list/<int:user_id>/',person_views.person_list,name='person_list'),

    #내가 쓴글
    path('list/',person_views.list,name='list'),
    path('detail/<int:question_id>',person_views.person_detail,name='person_detail'),
    path('person/question/modify/<int:question_id>/',person_views.person_question_modify, name='person_question_modify'),
    path('person/question/delete/<int:question_id>/',person_views.person_question_delete, name='person_question_delete'),
    #내가 답변한 글
    path('answer/list/',person_views.my_answer,name='my_answer'),
    path('answer/list/<int:question_id>',base_views.detail,name='my_answer_detail'),
    path('person/answer/modify/<int:answer_id>/',person_views.person_answer_modify, name='person_answer_modify'),
    path('person/answer/delete/<int:answer_id>/',person_views.person_answer_delete, name='person_answer_delete'),
    path('person/comment/create/answer/<int:answer_id>/', person_views.person_comment_create_answer, name='person_comment_create_answer'),
    path('person/comment/modify/answer/<int:comment_id>/', person_views.person_comment_modify_answer, name='person_comment_modify_answer'),
    path('person/comment/delete/answer/<int:comment_id>/', person_views.person_comment_delete_answer, name='person_comment_delete_answer'),
    #내가추천한글
    path('voter/list/',person_views.my_voter,name='my_voter'),


    path('url_test/',person_views.test, name='test'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    #외래키 추가
    #특정사용자가 작성한 질문 cur_user.author_question.all()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    #추천 User모델과 다대다관계
    #특정사용자가 투표한 질문 cur_user.voter_question.all()
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return self.subject

class Answer(models.Model):
    #Question을 외래키로 가짐.
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    voter = models.ManyToManyField(User, related_name='voter_answer')

    def __str__(self):
        return self.content

#댓글기능을 위한 모델
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question,null=True,blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer,null=True,blank=True,on_delete=models.CASCADE)
    #방명록기능을 위해 추가
    user = models.ManyToManyField(User,related_name='user_comment')

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect,resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.author = request.user
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form }

    return render(request,'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        #넌필드 오류발생시 사용
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail',question_id=answer.question.id)
    #폼객체 생성시 instance를 지정해주면 화면에 모델에 받아온 데이터를 뿌려주게 된다.
    if request.method=='POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date= timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'form':form}
    return render(request, 'pybo/answer_form.html',context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer= get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request,'삭제권한이 없습니다.')
        return redirect('pybo:detail',question_id=answer.question.id)
    answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from django.db.models import Q,Count

from ..models import Question

def index(request):
    #Get으로 페이지 가져옴 디폴트값은 1
    page = request.GET.get('page','1')
    #검색어 가져옴
    kw = request.GET.get('kw','')
    #정렬기준 가져옴
    so = request.GET.get('so','recent')


    #생성날짜 순으로 정렬해서 모델에서 가져옴
    question_list = Question.objects.order_by('-create_date')

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    #들어온 검색어로 검색.
    if kw:
        #제목, 내용 , 글쓴이, 답변이
        #filter함수에서는 모델속서에 접근하기위해 언더바두개씀
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw)  |
            Q(answer__author__username__icontains=kw)
        ).distinct() #

    #페이지처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj,'page':page,'kw':kw,'so':so}
    #데이터를 템플릿에 적용하여 HTML로 변환
    return render(request, 'pybo/question_list.html', context)

def detail(request,question_id):
    #1개만 가져옴 실패시 에러발생(all()의 경우 빈 쿼리셋 객체를 반환)
    #question = Question.objects.get(id=question_id)
    #못가져올시 404에러 발생
    question = get_object_or_404(Question, pk=question_id)

    answers=question.answer_set.order_by('-create_date').all()

    # Get으로 페이지 가져옴 디폴트값은 1
    page = request.GET.get('page', '1')

    paginator = Paginator(answers, 5)
    page_obj = paginator.get_page(page)

    context = {'question':question,'answer_list':page_obj}
    return render(request,'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Question, Answer, Comment

@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    pybo 질문댓글등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    pybo 질문댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('{}#comment_{}'.format(
            resolve_url('pybo:detail', question_id=comment.question.id), comment.id))

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    pybo 질문댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.question_id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question_id)

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
    pybo 답글댓글등록
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
    pybo 답글댓글수정
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('{}#comment_{}'.format(
            resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
    pybo 답글댓글삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question

@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        #html로 부터 전달받은 데이터를 form객체에 저장
        form = QuestionForm(request.POST)
        #전송된 입력값들이 유효한지 검사 만약 유효하지 않다면 form객체에 저장되어 리턴됨.
        if form.is_valid():
            question = form.save(commit=False) #폼을 통해 생성된 객체만 Question모델에다가 리턴해줌
            question.create_date = timezone.now()
            question.author = request.user
            question.save() #db에 저장
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form':form}
    return render(request,'pybo/question_form.html',context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        #넌필드 오류발생시 사용
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail',question_id=question_id)
    #폼객체 생성시 instance를 지정해주면 화면에 모델에 받아온 데이터를 뿌려주게 된다.
    if request.method=='POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date= timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)
    context = {'form':form}
    return render(request, 'pybo/question_form.html',context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question= get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request,'삭제권한이 없습니다.')
        return redirect('pybo:detail',question_id=question_id)
    question.delete()
    return redirect('pybo:index')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question,Answer


@login_required(login_url='common:login')
def vote_question(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

@login_required(login_url='common:login')
def vote_answer(request,answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" 
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content" 
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<script>
    $(document).ready(function(){
        $(".delete").on('click', function(){
            if(confirm("정말로 삭제하시겠습니까?")){
                location.href=$(this).data('uri');
            }
        });

        $(".recommend").on('click',function(){
            if(confirm("정말로 추천하시겠습니까?")){
                location.href=$(this).data('uri');
            }
        });

    });
</script>

<div class="container my-3">
    <!-- 사용자오류 표시 -->
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
        </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
            <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
    <div class="col-11">
        <div class="card">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    <div class="mb-2">{{ question.author.username }}</div>
                    {{ question.create_date|datetime }}
                    {% if question.modify_date %}
                    (수정:{{ question.modify_date|datetime }})
                    {% endif %}
                </div>
            </div>
            {% if question.author == request.user %}
            <div class="my-3">
                <a href="{% url 'pybo:question_modify' question.id %}"
                class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" data-uri="{% url 'pybo:question_delete' question.id %}"
                class="delete btn btn-sm btn-outline-secondary">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
    <!-- 질문 댓글 Start -->
    {% if question.comment_set.count > 0 %}
    <div class="mt-3">
    {% for comment in question.comment_set.all %}
        <a name="comment_{{ comment.id }}"></a>
        <div class="comment py-2 text-muted">
            <span style="white-space: pre-line;">{{ comment.content }}</span>
            <span>
                - {{ comment.author }}, {{ comment.create_date|datetime }}
                {% if comment.modify_date %}
                (수정:{{ comment.modify_date|datetime }})
                {% endif %}
            </span>
            {% if request.user == comment.author %}
            <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">수정</a>,
            <a href="#" class="small delete"
               data-uri="{% url 'pybo:comment_delete_question' comment.id %}">삭제</a>
            {% endif %}
        </div>
    {% endfor %}
    </div>
    {% endif %}
    <div>
        <a href="{% url 'pybo:comment_create_question' question.id %}"
           class="small"><small>댓글 추가 ..</small></a>
    </div>
    <!-- 질문 댓글 End -->

    <!-- 질문 답변 Start-->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in answer_list %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
            <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id  %}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>

        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            {{ answer.create_date|datetime }}
                            {% if answer.modify_date %}
                            {{ answer.modify_date }}
                            {% endif %}
                        </div>
                    </div>
                    {% if answer.author == request.user %}
                    <div class="my-3">
                        <a href="{% url 'pybo:answer_modify' answer.id %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" data-uri="{% url 'pybo:answer_delete' answer.id %}"
                           class="delete btn btn-sm btn-outline-secondary">삭제</a>
                    </div>
                    {% endif %}

                    <!-- 답변 댓글 Start -->
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date|datetime }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date|datetime }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                            data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>

                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_answer' answer.id %}"
                        class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!-- 답변 댓글 End -->
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if answer_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ 1 }}"> << </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ answer_list.previous_page_number }}"> < </a>
        </li>
        {% else %}
         <li class="page-item disabled">
            <a class="page-link"> << </a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true"> < </a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in answer_list.paginator.page_range %}
            {% if page_number >= answer_list.number|add:-5 and page_number <= answer_list.number|add:5 %}
            {% if page_number == answer_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ answer_list.next_page_number }}"> > </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ answer_list.paginator.count }}"> >> </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> > </a>
        </li>
        <li class="page-item disabled">
            <a class="page-link"> >> </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->


    <!-- 질문 답변 End -->

    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}

        <div class="form-group">
            <textarea {% if not user.is_authenticated %} disabled {% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>


{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!--아래태그로 자동적으로 입력항목이 생성된다.-->
        <!--{{ form.as_p }}-->
        <!--직접 폼html작성-->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}