config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo.views import base_views

urlpatterns = [
    #/으로 접속시 pybo의 index로 연결되도록
    path('',base_views.index, name='index'),
    path('admin/', admin.site.urls),
    #pybo url을 호출하면 views.py의 index라는 함수를 호출
    #항상 끝에 정규화를 위해 / 를 붙여주자
    #path('pybo/', views.index),
    #pybo url이 요청되면 pybov폴더의 urls.py의 매핑정보를 읽으라는 뜻.
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')), #로그인/아웃을 위한 url추가

]

pybo/urls.py
from django.urls import path

#from . import views
from .views import base_views,answer_views,question_views,comment_views,vote_views,person_views

#앱을 구분하기 위한 이름.(네임스페이스)
app_name = 'pybo'

urlpatterns=[
    #name은 별칭을 말함.html에서 별칭을 사용할 수 있음.
    #pybo가 생략된 이유는 config/urls.py에 이미 명시되어 있기 때문.
    path('',base_views.index, name='index'),
    #상세조회
    path('<int:question_id>/',base_views.detail, name='detail'),
    #답변등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #답변수정
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify, name='answer_modify'),
    #딥뱐삭제
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete, name='answer_delete'),
    #질문등록
    path('question/create/', question_views.question_create,name='question_create'),
    #질문수정
    path('question/modify/<int:question_id>/',question_views.question_modify, name='question_modify'),
    #질문삭제
    path('question/delete/<int:question_id>/',question_views.question_delete, name='question_delete'),
    #댓글 작성,수정,삭제
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    #추천기능
    path('vote/quetion/<int:question_id>/',vote_views.vote_question,name='vote_question'),
    path('vote/answer/<int:answer_id>/',vote_views.vote_answer,name='vote_answer'),

    #특정사용자가 쓴글
    path('person/list/<int:user_id>/',person_views.person_list,name='person_list'),

    #내가 쓴글
    path('list/',person_views.list,name='list'),
    path('detail/<int:question_id>',person_views.person_detail,name='person_detail'),
    path('person/question/modify/<int:question_id>/',person_views.person_question_modify, name='person_question_modify'),
    path('person/question/delete/<int:question_id>/',person_views.person_question_delete, name='person_question_delete'),
    #내가 답변한 글
    path('answer/list/',person_views.my_answer,name='my_answer'),
    path('answer/list/<int:question_id>',base_views.detail,name='my_answer_detail'),
    path('person/answer/modify/<int:answer_id>/',person_views.person_answer_modify, name='person_answer_modify'),
    path('person/answer/delete/<int:answer_id>/',person_views.person_answer_delete, name='person_answer_delete'),
    path('person/comment/create/answer/<int:answer_id>/', person_views.person_comment_create_answer, name='person_comment_create_answer'),
    path('person/comment/modify/answer/<int:comment_id>/', person_views.person_comment_modify_answer, name='person_comment_modify_answer'),
    path('person/comment/delete/answer/<int:comment_id>/', person_views.person_comment_delete_answer, name='person_comment_delete_answer'),
    #내가추천한글
    path('voter/list/',person_views.my_voter,name='my_voter'),


    path('url_test/',person_views.test, name='test'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    #외래키 추가
    #특정사용자가 작성한 질문 cur_user.author_question.all()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    #추천 User모델과 다대다관계
    #특정사용자가 투표한 질문 cur_user.voter_question.all()
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return self.subject

class Answer(models.Model):
    #Question을 외래키로 가짐.
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    voter = models.ManyToManyField(User, related_name='voter_answer')

    def __str__(self):
        return self.content

#댓글기능을 위한 모델
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question,null=True,blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer,null=True,blank=True,on_delete=models.CASCADE)
    #방명록기능을 위해 추가
    user = models.ManyToManyField(User,related_name='user_comment')

pybo/views/person_views.py
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required


from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect,resolve_url
from django.utils import timezone


from ..forms import QuestionForm, AnswerForm, CommentForm
from django.contrib.auth.models import User
from ..models import Question, Answer, Comment

import json

@login_required(login_url='common:login')
def list(request):

    page = request.GET.get('page','1')

    question = Question.objects.filter(author=request.user).order_by('-create_date')

    paginator = Paginator(question,10)
    page_obj = paginator.get_page(page)

    context = {"question_list" : page_obj,'page':page}
    return render(request, 'person/list.html',context)

@login_required(login_url='common:login')
def my_answer(request):
    page = request.GET.get('page', '1')

    answer=Answer.objects.filter(author=request.user).order_by('-create_date')

    length = len(answer)

    paginator = Paginator(answer, 10)
    page_obj = paginator.get_page(page)

    context = {"answer_list": page_obj, 'page': page,'total':length}
    return render(request, 'person/my_answer_list.html', context)


@login_required(login_url='common:login')
def my_voter(request):
    page = request.GET.get('page', '1')

    question = Question.objects.filter(voter=request.user).order_by('-create_date')


    paginator = Paginator(question, 10)
    page_obj = paginator.get_page(page)

    context = {"voter_list": page_obj, 'page': page}
    return render(request, 'person/my_voter_list.html', context)


def person_list(request,user_id):
    page = request.GET.get('page', '1')

    question = Question.objects.filter(author=user_id).order_by('-create_date')

    paginator = Paginator(question, 10)
    page_obj = paginator.get_page(page)

    context = {"question_list": page_obj, 'page': page}
    return render(request, 'person/list.html', context)

@login_required(login_url='common:login')
def person_detail(request,question_id):
    # 1개만 가져옴 실패시 에러발생(all()의 경우 빈 쿼리셋 객체를 반환)
    # question = Question.objects.get(id=question_id)
    # 못가져올시 404에러 발생
    question = get_object_or_404(Question, pk=question_id)

    answers = question.answer_set.order_by('-create_date').all()

    # Get으로 페이지 가져옴 디폴트값은 1
    page = request.GET.get('page', '1')

    paginator = Paginator(answers, 5)
    page_obj = paginator.get_page(page)

    context = {'question': question, 'answer_list': page_obj}
    return render(request, 'person/detail.html', context)


@login_required(login_url='common:login')
def person_question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    #폼객체 생성시 instance를 지정해주면 화면에 모델에 받아온 데이터를 뿌려주게 된다.
    if request.method=='POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date= timezone.now()
            question.save()
            return redirect('pybo:person_detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)
    context = {'form':form}
    return render(request, 'pybo/question_form.html',context)

@login_required(login_url='common:login')
def person_question_delete(request, question_id):
    question= get_object_or_404(Question, pk=question_id)
    question.delete()
    return redirect('pybo:list')

@login_required(login_url='common:login')
def person_answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)

    #폼객체 생성시 instance를 지정해주면 화면에 모델에 받아온 데이터를 뿌려주게 된다.
    if request.method=='POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date= timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(
                resolve_url('pybo:my_answer'), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'form':form}
    return render(request, 'pybo/answer_form.html',context)

@login_required(login_url='common:login')
def person_answer_delete(request, answer_id):
    answer= get_object_or_404(Answer, pk=answer_id)
    answer.delete()
    return redirect('pybo:my_answer')

@login_required(login_url='common:login')
def person_comment_create_answer(request, answer_id):

    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:my_answer'), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def person_comment_modify_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('pybo:my_answer'), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def person_comment_delete_answer(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('pybo:my_answer')

@login_required(login_url='common:login')
def test(request):
    question_id= request.POST.get('question_id')
    print('pk',question_id)
    q=get_object_or_404(Question,pk=question_id)

    context={ 'id': q.id,'subject':q.subject,'content':q.content,'create_date':str(q.create_date),'modify_date':str(q.modify_date),'author':q.author_id }

    return HttpResponse(json.dumps(context), content_type='application/json')

templates/person/detail.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<script>
    $(document).ready(function(){
        $(".delete").on('click', function(){
            if(confirm("정말로 삭제하시겠습니까?")){
                location.href=$(this).data('uri');
            }
        });

    });
</script>

<div class="container my-3">
    <!-- 사용자오류 표시 -->
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
        </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
        </div>
    <div class="col-11">
        <div class="card">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    <div class="mb-2">{{ question.author.username }}</div>
                    {{ question.create_date|datetime }}
                    {% if question.modify_date %}
                    (수정:{{ question.modify_date|datetime }})
                    {% endif %}
                </div>
            </div>
            {% if question.author == request.user %}
            <div class="my-3">
                <a href="{% url 'pybo:person_question_modify' question.id %}"
                class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" data-uri="{% url 'pybo:person_question_delete' question.id %}"
                class="delete btn btn-sm btn-outline-secondary">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
    <!-- 질문 댓글 Start -->
    {% if question.comment_set.count > 0 %}
    <div class="mt-3">
    {% for comment in question.comment_set.all %}
        <a name="comment_{{ comment.id }}"></a>
        <div class="comment py-2 text-muted">
            <span style="white-space: pre-line;">{{ comment.content }}</span>
            <span>
                - {{ comment.author }}, {{ comment.create_date|datetime }}
                {% if comment.modify_date %}
                (수정:{{ comment.modify_date|datetime }})
                {% endif %}
            </span>
            {% if request.user == comment.author %}
            <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">수정</a>,
            <a href="#" class="small delete"
               data-uri="{% url 'pybo:comment_delete_question' comment.id %}">삭제</a>
            {% endif %}
        </div>
    {% endfor %}
    </div>
    {% endif %}
    <div>
        <a href="{% url 'pybo:comment_create_question' question.id %}"
           class="small"><small>댓글 추가 ..</small></a>
    </div>
    <!-- 질문 댓글 End -->

    <!-- 질문 답변 Start-->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in answer_list %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
            <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id  %}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>

        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            {{ answer.create_date|datetime }}
                            {% if answer.modify_date %}
                            {{ answer.modify_date }}
                            {% endif %}
                        </div>
                    </div>
                    {% if answer.author == request.user %}
                    <div class="my-3">
                        <a href="{% url 'pybo:answer_modify' answer.id %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" data-uri="{% url 'pybo:answer_delete' answer.id %}"
                           class="delete btn btn-sm btn-outline-secondary">삭제</a>
                    </div>
                    {% endif %}

                    <!-- 답변 댓글 Start -->
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date|datetime }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date|datetime }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                            data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>

                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_answer' answer.id %}"
                        class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!-- 답변 댓글 End -->
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if answer_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ 1 }}"> << </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ answer_list.previous_page_number }}"> < </a>
        </li>
        {% else %}
         <li class="page-item disabled">
            <a class="page-link"> << </a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true"> < </a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in answer_list.paginator.page_range %}
            {% if page_number >= answer_list.number|add:-5 and page_number <= answer_list.number|add:5 %}
            {% if page_number == answer_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ answer_list.next_page_number }}"> > </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ answer_list.paginator.count }}"> >> </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> > </a>
        </li>
        <li class="page-item disabled">
            <a class="page-link"> >> </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->


    <!-- 질문 답변 End -->

    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}

        <div class="form-group">
            <textarea {% if not user.is_authenticated %} disabled {% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>


{% endblock %}

templates/person/my_answer_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $(".delete").on('click', function(){
            if(confirm("정말로 삭제하시겠습니까?")){
                location.href=$(this).data('uri');
            }
        });

    $(".lead").click(function(){
        var pk = $(this).attr('name')
        var cur = $(this)
        $.ajax({ // .like 버튼을 클릭하면 <새로고침> 없이 ajax로 서버와 통신하겠다.
              type: "POST", // 데이터를 전송하는 방법을 지정
              url: "{% url 'pybo:test' %}", // 통신할 url을 지정
              data: {'question_id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터 전송시 옵션
              dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정, 없으면 알아서 판단
              // 서버측에서 전송한 Response 데이터 형식 (json)
              //{ 'id': q.id,'subject':q.subject,'content':q.content,'create_date':str(q.create_date),'modify_date':str(q.modify_date),'author':q.author_id }
              success: function(response){ // 통신 성공시 - 동적으로 좋아요 갯수 변경, 유저 목록 변경

                var url = response.id
                cur.empty()
                cur.append('<p>'+response.subject+'</p>')
                cur.append("<a href="+url+"><p>"+response.content+'</p></a>')
              },
              error: function(request, status, error){ // 통신 실패시 - 로그인 페이지 리다이렉트
                //  alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
              },
        });
    })
});
</script>



<div class="container my-3">
<h5 class="border-bottom my-3 py-2">{{ total }}개의 답변을 했습니다.</h5>
    {% for answer in answer_list %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
        </div>
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <p class="lead" name="{{ answer.question.id }}" >
                        <small>....</small>
                    </p>
                    <div class="comment py-2 text-muted"/>
                    </div>
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            {{ answer.create_date|datetime }}
                            {% if answer.modify_date %}
                            {{ answer.modify_date }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="my-3">
                        <a href="{% url 'pybo:person_answer_modify' answer.id %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" data-uri="{% url 'pybo:person_answer_delete' answer.id %}"
                           class="delete btn btn-sm btn-outline-secondary">삭제</a>
                    </div>

                    <!-- 답변 댓글 Start -->
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date|datetime }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date|datetime }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:person_comment_modify_answer' comment.id %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                            data-uri="{% url 'pybo:person_comment_delete_answer' comment.id %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>

                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:person_comment_create_answer' answer.id %}"
                        class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!-- 답변 댓글 End -->
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if answer_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ 1 }}" href="#"> << </a>
        </li>
        <li class="page-item">
            <a class="page-link" data-page="{{ answer_list.previous_page_number }}" href="#"> < </a>
        </li>
        {% else %}
         <li class="page-item disabled">
            <a class="page-link"> << </a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> < </a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in answer_list.paginator.page_range %}
            {% if page_number >= answer_list.number|add:-5 and page_number <= answer_list.number|add:5 %}
            {% if page_number == answer_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}"href="#" >{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if answer_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ answer_list.next_page_number }}" href="#"> > </a>
        </li>
        <li class="page-item">
            <a class="page-link" data-page="{{ answer_list.paginator.count }}" href="#" > >> </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"> > </a>
        </li>
        <li class="page-item disabled">
            <a class="page-link"> >> </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'pybo:my_answer' %}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
</div>
{% endblock %}