common/urls.py
from django.urls import path, include

from django.contrib.auth import views as auth_views

from . import views
app_name = 'common'

urlpatterns=[
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view() ,name='logout'),
    path('signup/', views.signup ,name='signup'),
    path('find/password/',views.findpassword,name='findpassword'),
    path('profile/',views.profile,name='profile'),
    # 방명록
    path('visitor/', views.visitor, name='visitor'),
    # 코로나 현황
    path('covid/',views.covid, name='covid'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo.views import base_views

urlpatterns = [
    #/으로 접속시 pybo의 index로 연결되도록
    path('',base_views.index, name='index'),
    path('admin/', admin.site.urls),
    #pybo url을 호출하면 views.py의 index라는 함수를 호출
    #항상 끝에 정규화를 위해 / 를 붙여주자
    #path('pybo/', views.index),
    #pybo url이 요청되면 pybov폴더의 urls.py의 매핑정보를 읽으라는 뜻.
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')), #로그인/아웃을 위한 url추가

]

pybo/urls.py
from django.urls import path

#from . import views
from .views import base_views,answer_views,question_views,comment_views,vote_views,person_views

#앱을 구분하기 위한 이름.(네임스페이스)
app_name = 'pybo'

urlpatterns=[
    #name은 별칭을 말함.html에서 별칭을 사용할 수 있음.
    #pybo가 생략된 이유는 config/urls.py에 이미 명시되어 있기 때문.
    path('',base_views.index, name='index'),
    #상세조회
    path('<int:question_id>/',base_views.detail, name='detail'),
    #답변등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #답변수정
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify, name='answer_modify'),
    #딥뱐삭제
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete, name='answer_delete'),
    #질문등록
    path('question/create/', question_views.question_create,name='question_create'),
    #질문수정
    path('question/modify/<int:question_id>/',question_views.question_modify, name='question_modify'),
    #질문삭제
    path('question/delete/<int:question_id>/',question_views.question_delete, name='question_delete'),
    #댓글 작성,수정,삭제
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    #추천기능
    path('vote/quetion/<int:question_id>/',vote_views.vote_question,name='vote_question'),
    path('vote/answer/<int:answer_id>/',vote_views.vote_answer,name='vote_answer'),

    #특정사용자가 쓴글
    path('person/list/<int:user_id>/',person_views.person_list,name='person_list'),

    #내가 쓴글
    path('list/',person_views.list,name='list'),
    path('detail/<int:question_id>',person_views.person_detail,name='person_detail'),
    path('person/question/modify/<int:question_id>/',person_views.person_question_modify, name='person_question_modify'),
    path('person/question/delete/<int:question_id>/',person_views.person_question_delete, name='person_question_delete'),
    #내가 답변한 글
    path('answer/list/',person_views.my_answer,name='my_answer'),
    path('answer/list/<int:question_id>',base_views.detail,name='my_answer_detail'),
    path('person/answer/modify/<int:answer_id>/',person_views.person_answer_modify, name='person_answer_modify'),
    path('person/answer/delete/<int:answer_id>/',person_views.person_answer_delete, name='person_answer_delete'),
    path('person/comment/create/answer/<int:answer_id>/', person_views.person_comment_create_answer, name='person_comment_create_answer'),
    path('person/comment/modify/answer/<int:comment_id>/', person_views.person_comment_modify_answer, name='person_comment_modify_answer'),
    path('person/comment/delete/answer/<int:comment_id>/', person_views.person_comment_delete_answer, name='person_comment_delete_answer'),
    #내가추천한글
    path('voter/list/',person_views.my_voter,name='my_voter'),


    path('url_test/',person_views.test, name='test'),
]

common/models.py
from django.db import models

pybo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    #외래키 추가
    #특정사용자가 작성한 질문 cur_user.author_question.all()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    #추천 User모델과 다대다관계
    #특정사용자가 투표한 질문 cur_user.voter_question.all()
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return self.subject

class Answer(models.Model):
    #Question을 외래키로 가짐.
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    voter = models.ManyToManyField(User, related_name='voter_answer')

    def __str__(self):
        return self.content

#댓글기능을 위한 모델
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question,null=True,blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer,null=True,blank=True,on_delete=models.CASCADE)
    #방명록기능을 위해 추가
    user = models.ManyToManyField(User,related_name='user_comment')

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

#UserCreationForm의 속성 username,password1, password2
#is_valid()함수 호출시 위 3개를 체크함.
class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')

    class Meta:
        model = User
        fields = ('username','email')

class FindPasswordForm(forms.ModelForm):

    class Meta:
        model = User
        #속성설정.
        fields =['username','email']

        labels={
            'username':'아이디',
            'email':'이메일',
        }

common/views.py
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.shortcuts import render,redirect
from common.forms import UserForm,FindPasswordForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .commonUtils import getTempPassword,send_email

import requests
import time
from urllib.parse import unquote
import xml.etree.ElementTree as el


@login_required(login_url='common:login')
def profile(request):
    return render(request, 'common/profile.html')

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    context={'form':form}
    return render(request, 'common/signup.html', context)


def findpassword(request):

    if request.method == 'POST':
        form = FindPasswordForm(request.POST)
        username = request.POST.get('username')
        email = request.POST.get('email')

        if User.objects.filter(email=email).filter(username=username).exists():
            #맞는 정보를 찾음
            #임시비밀번호로 변경.
            temppassword=getTempPassword()
            u = User.objects.get(username=username)
            u.set_password(temppassword)
            u.save()
            send_email(email,'메일주소변경안내',temppassword)
        else:
            #못찾음
            messages.error(request, '아이디와 이메일을 다시 입력해주세요.')
            return redirect('common:findpassword')
    else:
        form = FindPasswordForm()
    context={"form":form}
    return render(request, 'common/findpassword.html', context)

def visitor(request):

    return render(request,'common/visitor.html')



def covid(request):

    serviceUrl = 'http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19SidoInfStateJson'
    serviceKey = 'XhXhzNW%2BV19VmW1IWKHPOt5mBgvHbcSxIHHtZcWKjFZwR5PPIAk%2Fn%2FqAyS9hybxU2TPYPmka6MQYYDdReAMmJw%3D%3D'
    serviceKey_decode = unquote(serviceKey)

    pageNo = '2'
    numOfRows = '10'
    startCreateDt = '20200901'
    endCreateDt = time.strftime('%Y%m%d', time.localtime(time.time()))

    parameters = {"serviceKey": serviceKey_decode, "pageNo": pageNo, "numOfRows": numOfRows,
                  "startCreateDt": startCreateDt, "endCreateDt": endCreateDt}

    response = requests.get(serviceUrl, params=parameters)

    print(response.text)

    covidList=[]

    if response.status_code == 200:
        # print("응닫결과 : ",response.text)
        tree = el.fromstring(response.text)
        iter = tree.iter(tag="item")

        for element in iter:

            createDt = element.find('createDt')  # 일시
            deathCnt = element.find('deathCnt')  # 사망자
            area = element.find('gubun')  # 지역
            inDec = element.find('incDec')  # 전일대비증감수
            defCnt = element.find('defCnt')  # 확진자수
            isolClearCnt = element.find('isolClearCnt')  # 격리해제수
            isolIngCnt = element.find('isolIngCnt')  # 격리중환자수
            localOccCnt = element.find('localOccCnt')  # 지역발생수
            overFlowCnt = element.find('overFlowCnt')  # 해외유입수
            qurRate = element.find('qurRate')  # 10만명당 발생률
            id = element.find('seq')  # 게시글번호(고유값)
            stdDay = element.find('stdDay')  # 기준일시
            updateDt  = element.find('updateDt ')  # 수정일시
            data = {"createDt":createDt.text,"deathCnt":deathCnt.text,"area":area.text,"inDec":inDec.text,"isolClearCnt":isolClearCnt.text
                ,"isolIngCnt":isolIngCnt.text,"localOccCnt":localOccCnt.text,"overFlowCnt":overFlowCnt.text,"qurRate":qurRate.text,
                "id":id.text,"stdDay":stdDay.text,"defCnt":defCnt.text}
            covidList.append(data)

    context = {'covidList': covidList}
    print(covidList)
    return render(request,'common/covid.html',context)

templates/common/covid.html
{% extends 'base.html' %}
{% block content %}

{% if covidList %}
    {% for data in covidList %}

        작성 날짜 : {{ data.createDt }} <br>
        지역 : {{ data.area }}<br>
        사망자 : {{ data.deathCnt }}<br>
        확진자 수 : {{ data.defCnt }}<br>
        전일 대비 증감 수 : {{ data.inDec }}<br>
        격리 해제 수 : {{ data.isolClearCnt }}<br>
        격리 중 환자 수 : {{ data.isolIngCnt }}<br>
        지역 발생 수 : {{ data.localOccCnt }}<br>
        해외 유입 수 : {{ data.overFlowCnt }}<br>
        기준 일시 : {{ data.stdDay }}<br>

        {% if data.updateDt %}
            수정 날짜 : {{ data.updateDt }}<br>
        {% else %}
            수정 날짜 : 없음<br>
        {% endif %}
        ------------------------<br>



    {% endfor %}

{% endif %}


{% endblock %}

templates/common/findpassword.html
{% extends 'base.html' %}
{% block content %}

    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
        </div>
    {% endif %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">비밀번호찾기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="email" class="form-control" name="email" id="email">
        </div>
        <button type="submit" class="btn btn-primary">비밀번호찾기</button>
    </form>
</div>


{% endblock %}

templates/common/login.html
{% extends "base.html" %}
{% block content %}

<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
        <a href="{% url 'common:findpassword' %}"><span class="text-info middle ml-2">비밀번호 찾기</span></a>
    </form>

</div>

{% endblock %}

templates/common/profile.html
{% extends 'base.html' %}
{% load pybo_filter %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'profile.css' %}">
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

<body>
    <div class="container main-secction">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 image-section">
                <img src="https://png.pngtree.com/thumb_back/fw800/back_pic/00/08/57/41562ad4a92b16a.jpg">
            </div>
            <div class="row user-left-part">
                <div class="col-md-3 col-sm-3 col-xs-12 user-profil-part pull-left">
                    <div class="row ">
                        <div class="col-md-12 col-md-12-sm-12 col-xs-12 user-image text-center">
                            <img src="https://www.jamf.com/jamf-nation/img/default-avatars/generic-user-purple.png" class="rounded-circle">
                        </div>
                        <div class="col-md-12 col-sm-12 col-xs-12 user-detail-section1 text-center">
                            <button id="btn-contact" (click)="clearModal()" data-toggle="modal" data-target="#contact" class="btn btn-success btn-block follow">Contactarme</button>
                            <button class="btn btn-warning btn-block">노란버튼</button>
                        </div>
                        <div class="row user-detail-row">
                            <div class="col-md-12 col-sm-12 user-detail-section2 pull-left">
                                <div class="border"></div>
                                <p>...</p>
                                <span>...</span>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-md-9 col-sm-9 col-xs-12 pull-right profile-right-section">
                    <div class="row profile-right-section-row">
                        <div class="col-md-12 profile-header">
                            <div class="row">
                                <div class="col-md-8 col-sm-6 col-xs-6 profile-header-section1 pull-left">
                                    <h1>{{ request.user.username }}</h1>
                                    <h5>회원</h5>
                                </div>
                                <div class="col-md-4 col-sm-6 col-xs-6 profile-header-section1 text-right pull-rigth">
                                    <a href="{% url 'pybo:person_list' request.user.id %}" class="btn btn-primary btn-block">쓴 글</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-8">
                                        <ul class="nav nav-tabs" role="tablist">
                                                <li class="nav-item">
                                                  <a class="nav-link active" href="#profile" role="tab" data-toggle="tab"><i class="fas fa-user-circle"></i>내 정보</a>
                                                </li>
                                                <li class="nav-item">
                                                  <a class="nav-link" href="#buzz" role="tab" data-toggle="tab"><i class="fas fa-info-circle"></i> 상세정보

                                                  </a>
                                                </li>
                                              </ul>

                                              <!-- Tab panes -->
                                              <div class="tab-content">
                                                <div role="tabpanel" class="tab-pane fade show active" id="profile">
                                                        <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>고유번호</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>{{ request.user.id }}</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>닉네임</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>{{ request.user.username }}_{{ request.user.id }}</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>Email</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>{{ request.user.email }}</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>전화번호</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>12345678</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-2">
                                                                    <label>직업</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>Developer</p>
                                                                </div>
                                                            </div>
                                                </div>
                                                <div role="tabpanel" class="tab-pane fade" id="buzz">
                                                        <div class="row">
                                                                <div class="col-md-6">
                                                                    <label>Experience</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>Expert</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-6">
                                                                    <label>Hourly Rate</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>10$/hr</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-6">
                                                                    <label>Total Projects</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>230</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-6">
                                                                    <label>English Level</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>Expert</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-6">
                                                                    <label>Availability</label>
                                                                </div>
                                                                <div class="col-md-6">
                                                                    <p>6 months</p>
                                                                </div>
                                                            </div>
                                                            <div class="row">
                                                                <div class="col-md-12">
                                                                    <label>Your Bio</label>
                                                                    <br/>
                                                                    <p>Your detail description</p>
                                                                </div>
                                                            </div>
                                                </div>

                                              </div>

                                </div>
                                <div class="col-md-4 img-main-rightPart">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="row image-right-part">
                                                <div class="col-md-6 pull-left image-right-detail">
                                                    <h6>...</h6>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-md-12 image-right-detail-section2">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="contact" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="contact">Contactarme</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <p for="msj">Se enviará este mensaje a la persona que desea contactar, indicando que te quieres comunicar con el. Para esto debes de ingresar tu información personal.</p>
                    </div>
                    <div class="form-group">
                        <label for="txtFullname">Nombre completo</label>
                        <input type="text" id="txtFullname" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="txtEmail">Email</label>
                        <input type="text" id="txtEmail" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="txtPhone">Teléfono</label>
                        <input type="text" id="txtPhone" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
                    <button type="button" class="btn btn-primary" (click)="openModal()" data-dismiss="modal">보내기</button>
                </div>
            </div>
        </div>
    </div>
</body>


{% endblock %}

templates/common/visitor.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}

<div class="container my-3">
<h5 class="border-bottom my-3 py-2">{{ total }}개의 답변을 했습니다.</h5>
    {% for answer in answer_list %}
    <a name="answer_{{ answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
        </div>
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <p class="lead" name="{{ answer.question.id }}" >
                        <small>....</small>
                    </p>
                    <div class="comment py-2 text-muted"/>
                    </div>
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2">
                            <div class="mb-2">{{ answer.author.username }}</div>
                            {{ answer.create_date|datetime }}
                            {% if answer.modify_date %}
                            {{ answer.modify_date }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="my-3">
                        <a href="{% url 'pybo:person_answer_modify' answer.id %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" data-uri="{% url 'pybo:person_answer_delete' answer.id %}"
                           class="delete btn btn-sm btn-outline-secondary">삭제</a>
                    </div>

                    <!-- 답변 댓글 Start -->
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.author }}, {{ comment.create_date|datetime }}
                                {% if comment.modify_date %}
                                (수정:{{ comment.modify_date|datetime }})
                                {% endif %}
                            </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:person_comment_modify_answer' comment.id %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                            data-uri="{% url 'pybo:person_comment_delete_answer' comment.id %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>

                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:person_comment_create_answer' answer.id %}"
                        class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!-- 답변 댓글 End -->
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}