common/urls.py
from django.urls import path, include

from django.contrib.auth import views as auth_views

from . import views
app_name = 'common'

urlpatterns=[
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view() ,name='logout'),
    path('signup/', views.signup ,name='signup'),
    path('find/password/',views.findpassword,name='findpassword'),
    path('profile/',views.profile,name='profile'),
    # 방명록
    path('visitor/', views.visitor, name='visitor'),
    # 코로나 현황
    path('covid/',views.covid, name='covid'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo.views import base_views

urlpatterns = [
    #/으로 접속시 pybo의 index로 연결되도록
    path('',base_views.index, name='index'),
    path('admin/', admin.site.urls),
    #pybo url을 호출하면 views.py의 index라는 함수를 호출
    #항상 끝에 정규화를 위해 / 를 붙여주자
    #path('pybo/', views.index),
    #pybo url이 요청되면 pybov폴더의 urls.py의 매핑정보를 읽으라는 뜻.
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')), #로그인/아웃을 위한 url추가

]

pybo/urls.py
from django.urls import path

#from . import views
from .views import base_views,answer_views,question_views,comment_views,vote_views,person_views

#앱을 구분하기 위한 이름.(네임스페이스)
app_name = 'pybo'

urlpatterns=[
    #name은 별칭을 말함.html에서 별칭을 사용할 수 있음.
    #pybo가 생략된 이유는 config/urls.py에 이미 명시되어 있기 때문.
    path('',base_views.index, name='index'),
    #상세조회
    path('<int:question_id>/',base_views.detail, name='detail'),
    #답변등록
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #답변수정
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify, name='answer_modify'),
    #딥뱐삭제
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete, name='answer_delete'),
    #질문등록
    path('question/create/', question_views.question_create,name='question_create'),
    #질문수정
    path('question/modify/<int:question_id>/',question_views.question_modify, name='question_modify'),
    #질문삭제
    path('question/delete/<int:question_id>/',question_views.question_delete, name='question_delete'),
    #댓글 작성,수정,삭제
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    #추천기능
    path('vote/quetion/<int:question_id>/',vote_views.vote_question,name='vote_question'),
    path('vote/answer/<int:answer_id>/',vote_views.vote_answer,name='vote_answer'),

    #특정사용자가 쓴글
    path('person/list/<int:user_id>/',person_views.person_list,name='person_list'),

    #내가 쓴글
    path('list/',person_views.list,name='list'),
    path('detail/<int:question_id>',person_views.person_detail,name='person_detail'),
    path('person/question/modify/<int:question_id>/',person_views.person_question_modify, name='person_question_modify'),
    path('person/question/delete/<int:question_id>/',person_views.person_question_delete, name='person_question_delete'),
    #내가 답변한 글
    path('answer/list/',person_views.my_answer,name='my_answer'),
    path('answer/list/<int:question_id>',base_views.detail,name='my_answer_detail'),
    path('person/answer/modify/<int:answer_id>/',person_views.person_answer_modify, name='person_answer_modify'),
    path('person/answer/delete/<int:answer_id>/',person_views.person_answer_delete, name='person_answer_delete'),
    path('person/comment/create/answer/<int:answer_id>/', person_views.person_comment_create_answer, name='person_comment_create_answer'),
    path('person/comment/modify/answer/<int:comment_id>/', person_views.person_comment_modify_answer, name='person_comment_modify_answer'),
    path('person/comment/delete/answer/<int:comment_id>/', person_views.person_comment_delete_answer, name='person_comment_delete_answer'),
    #내가추천한글
    path('voter/list/',person_views.my_voter,name='my_voter'),


    path('url_test/',person_views.test, name='test'),
]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from django.db.models import Q,Count

from ..models import Question

def index(request):
    #Get으로 페이지 가져옴 디폴트값은 1
    page = request.GET.get('page','1')
    #검색어 가져옴
    kw = request.GET.get('kw','')
    #정렬기준 가져옴
    so = request.GET.get('so','recent')


    #생성날짜 순으로 정렬해서 모델에서 가져옴
    question_list = Question.objects.order_by('-create_date')

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    #들어온 검색어로 검색.
    if kw:
        #제목, 내용 , 글쓴이, 답변이
        #filter함수에서는 모델속서에 접근하기위해 언더바두개씀
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw)  |
            Q(answer__author__username__icontains=kw)
        ).distinct() #

    #페이지처리
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj,'page':page,'kw':kw,'so':so}
    #데이터를 템플릿에 적용하여 HTML로 변환
    return render(request, 'pybo/question_list.html', context)

def detail(request,question_id):
    #1개만 가져옴 실패시 에러발생(all()의 경우 빈 쿼리셋 객체를 반환)
    #question = Question.objects.get(id=question_id)
    #못가져올시 404에러 발생
    question = get_object_or_404(Question, pk=question_id)

    answers=question.answer_set.order_by('-create_date').all()

    # Get으로 페이지 가져옴 디폴트값은 1
    page = request.GET.get('page', '1')

    paginator = Paginator(answers, 5)
    page_obj = paginator.get_page(page)

    context = {'question':question,'answer_list':page_obj}
    return render(request,'pybo/question_detail.html', context)

templates/base.html
<!DOCTYPE html>

{% load static %}


<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'simple-sidebar.css' %}">
    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>

    <title>Hello, pybo!</title>
</head>
<body>
<!--네비게이션바-->
{% include 'navbar.html' %}

  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">{{ request.user.username }}</div>
      <div class="list-group list-group-flush">
        <a href="{% url 'common:visitor' %}" class="list-group-item list-group-item-action bg-light">방명록</a>
        <a href="{% url 'pybo:list' %}" class="list-group-item list-group-item-action bg-light">내가 쓴 글</a>
        <a href="{% url 'pybo:my_answer' %}" class="list-group-item list-group-item-action bg-light">내가 답변한 글</a>
        <a href="{% url 'pybo:my_voter' %}" class="list-group-item list-group-item-action bg-light">내가 추천한 글</a>
        <a href="{% url 'common:profile' %}" class="list-group-item list-group-item-action bg-light">내 정보</a>
        <a href="https://www.google.com" target="_blank" class="list-group-item list-group-item-action bg-light">도움말</a>
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
    </div>
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">

                {% if user.is_authenticated %}
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }}(로그아웃)</a>
                {% else %}
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'common:covid' %}">COVID-19 현황</a>
            </li>
        </ul>
    </div>
</nav>